name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt install openssh-client

      - name: Connect to server by ssh
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_IP_ADDRESS }}
          username: 'ubuntu'
          password: 'ShivaMurugan@3'
          port: 22
          script: |
            pwd
            cd /home/ubuntu/Daynighttours
            git fetch
            git pull origin
            composer install
            npm install
            npm run dev
