name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add build steps here (e.g., compiling code, running tests)

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt install openssh-client

      - uses: webfactory/ssh-agent@v0.7.0
        with:
            ssh-private-key: "MIIEowIBAAKCAQEAh8GnGKKEf8F4CZ87I0oIGFJ1CKlqa7/PZq0xxgTfdDdKUmhJIrTrYuSzUbkeZmmM3QrCi4u/qW7CyKT0RjkfXniOORUIgqLgFRKAmLf8dzZhNFkWwW6+eC5Y2hNPO3aKShDLI38Z42xnlQ7L0QIUTx3oU1wHSFESkmqsjUngWE2J8S2j/n/NtI18dpA/vHrl8zhE44rh5nTzPedbuQzR95Qm0UQbgB+rpJc4/X12DQQGUt5GcCGJpYCBuTopLQYk1WB/GFVjqmVftPsExNHDLTCR8pA/A/ChEw1605TkppnlUWVU+Hk6sKxNNjQea7ip3c8N7pXTF5y3/jm+6XfEvQIDAQABAoIBAA8b8Hr/a3vEjpWTkUNmM+xxEPF72YpQeMbWs9l0JWKL3Mu7K5ifRitlhMetsMJ5MOJRFkHttdEnsKogIcfHB8S96iZUPvQ7KHFv87wLjh++f6cR20SADNbXYbAzwfe+Q7nmkJVMyhbTs9uVH/4NGzGLBJZygaT80PJWyQmYlU1+ej6g+bqxDmmvN2oOBuAfxAFiORI376PjmcYuO0/OHSPqSE4LlEQDZddPnWiq3M/dnwFkt5WO+2YIhYdVcJYqTcNp1ekA2JtpplqFem/JW+NBwcnxAAUxEg4FgHfWOxaUJdVZmitmdB6+cTVpf+F6kC56cHZ5cdROGw1Nb9dp5IECgYEAv5OkjnxdKWweNSfXv4zOifQCnHeB+2amOOvjJGNr4pALl3Uk/y6dLVdG3+xA9NrT0eAKInecVOpLV2UTvPww2s7+GOsusJz8L6Ute6WiWGofiVLwFy975pkjK2cpa8TZliPEkhIIc72hPHeINET3TjjcoydFl888GF5xyRc/UK0CgYEAtWiVWwNEFfjqyFnUwawtF4RKa2hHcuUODiP38yyVvbSgoQmTn3TUWHEz0thef0Z1mMqU7lUWVcHhBG28tlSH7+enNrIAztckMc+CrKqHYeVVgcpGupmqLEsuYcR9VuETebvcuXV5tW3LQpaQxi1ogOGSx2dKUxZmrs6Vczqt9lECgYEAuGu34NaFlGeZWNBnF+XDufelP9yny0zQvUEPIyt2Yt8J2Z6So/jKpCg9eThke5HgkUxcVTvRycjWCGasLqSTnz/eSjy0cJ5fArq+4yXa98QJYdfuelNiseU/fvvLWwxf7fG2vGsRqeGlwqDLBI5TiACjHYijrPV5Q3g/jzaK4+0CgYBJqxzsBtmBasI9dm118Oum3ywxjfll6SraBzVL5VEx5sZMX005tgH9oIsBFqjZWs2qrKnqV1dooAE3ATFfgdhqTlKTXZoCZU/ngnN4lw+/a5hbyr8KTBjVP/qn7VlRDLoR935dOh2g1eNzOR21vP7xR6mJnKKMN06fsnjygGPg4QKBgETqqguhKAKmkA8/p3YPOUA826ciEUT9m7uO86timBGbZdosvCIkmKZBr6ld/uf0Y8Pxn2hKK9arMNgdEmmF5X7ej9AI6j3OoLqmdUIlXdbaYJwyfEJDHXfhff//lhG4QF1vJlJ9Bc0gzeYuj9mjDrIVs+Mg1VPNe8ZZ5aO8wx7B"

      - name: Install PHP dependencies
        run: cd /var/www/html && git pull origin master
      - name: Install PHP dependencies
        run: composer install

      - name: Deploy code
        run: npm run build
