name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add build steps here (e.g., compiling code, running tests)

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt install openssh-client

      - uses: webfactory/ssh-agent@v0.7.0
        with:
            ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Install PHP dependencies
        run: cd /var/www/html && git pull origin master
      - name: Install PHP dependencies
        run: composer install

      - name: Deploy code
        run: npm run build
